name: Zip and Push

on:
  push:
    paths:
      - "fsbu/data/**"  # Monitor for changes in fsbu/data
    branches:
      - main  # Only run on the main branch

jobs:
  zip_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Zip File
      run: |
        zip -r zipped-folder.zip fsbu/data  # Zip the fsbu/data folder

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push
      run: |
        mv zipped-folder.zip fsbu/data/zipped-folder.zip  # Move the zipped file to fsbu/data
        git add fsbu/data/zipped-folder.zip
        git commit -m "Add zipped folder"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
